DefaultContentLanguage = "es"
baseURL = ""
languageCode = "es-cr"
title = "Novatec Construcción"
[context.deploy-preview.environment]
HUGO_VERSION = "0.42.2"
[params]
cloudinary_url = "https://res.cloudinary.com/novatec/image/upload/"
