---
label: Productos
hide_body: false
display_field: title
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: id
  label: Id
  type: text
  hidden: false
  default: ''
- name: marcas
  label: Marcas
  type: tag_list
  hidden: false
  default: ''
- name: familias
  label: Familias
  type: tag_list
  hidden: false
  default: ''
- name: industrias
  label: Industrias
  type: tag_list
  hidden: false
  default: ''
- name: imagen
  label: Imagen
  type: file
  hidden: false
  default: ''
- name: catalogo
  label: Catalogo
  type: text
  hidden: false
  default: ''
- name: meta_description
  label: Meta description
  type: text
  hidden: false
  default: ''
- name: meta_keywords
  label: Meta keywords
  type: text
  hidden: false
  default: ''
- name: weight
  label: Weight
  type: text
  hidden: false
  default: ''
- name: taxonomyCover
  label: Taxonomycover
  type: boolean
  hidden: false
  default: ''
- name: galeria
  type: image_gallery
  config: {}
  label: Galería
  description: Imágenes adicionales para cada producto. Ancho mínimo 760px
- name: titulo_adicional
  type: text
  config:
    required: false
  label: Titulo adicional
pages:
- content/productos/_index.md
- content/productos/cementicios.md
- content/productos/curadores-selladores-acrilicos.md
- content/productos/curadores.md
- content/productos/endurecedores-liquidos.md
- content/productos/endurecedores.md
- content/productos/epoxicos.md
- content/productos/fibras-de-carbono-para-reparacion-estructural.md
- content/productos/fibras-para-refuerzo-de-concreto.md
- content/productos/impermeabilizacion-de-superficies.md
- content/productos/impermeabilizantes-asfalticos.md
- content/productos/impermeabilizantes-base-poliuretano.md
- content/productos/impermeabilizantes-cementicios.md
- content/productos/juntas-epoxicas.md
- content/productos/laminas-a-base-de-bentonita-para-muros.md
- content/productos/membranas.md
- content/productos/morteros.md
- content/productos/recubrimientos-1.md
- content/productos/recubrimientos-epoxicos.md
- content/productos/recubrimientos.md
- content/productos/retardante-de-evaporacion.md
- content/productos/sellos-de-bentonita.md
- content/productos/sellos-de-poliurea.md
- content/productos/sellos-de-poliuretano.md
- content/productos/titulo-de-producto-goes-her.md
- content/productos/vandex-super.md
- content/productos/vulkem-801.md
